### PR TITLE
Slice out of range

### PR DESCRIPTION
**Pull request by knitzsche**
when no ssids found, do the right thing in cases of nil or zero length
fixes https://github.com/CanonicalLtd/UCWifiConnect/issues/4
note: the snapcraft.yaml uses go-importpart combined with a new part for netman, thus allowing the pkg and the code that uses it to co-exists in the same feature branch.

### CODE REVIEW

**Comment by rmescandon** [comment]
mmm.. I don't see any file changed in this PR :(

**Comment by rmescandon** [comment]
Several things:
A) In case no SSID is found works perfectly
B) I cannot get the packages updated locally with this solution (am I doing something wrong?). However, if I move folders having external packages (netman and wifiap) into src and I have only one part using go plugin into snapcraft.yaml, this way:

go:
    plugin: go
    source: src
    go-importpath: github.com/CanonicalLtd/UCWifiConnect

that works.
C) Not related with this PR, but I saw if i cannot get system bus connection, the related error says "Failed to connect to session bus" :D. (That's into netman.ssids.go.getSystemBus())

**Comment by knitzsche** [comment]
Hi Roberto, all fixed.

**Comment by rmescandon** [comment]
Just a final detail. Can you remove commented out netman-pkg part in snapcraft.yaml?

**Comment by knitzsche** [comment]
snapcraft.yaml comments removed

**Pull request merged**
