### PR TITLE
Daemon

### PR DESCRIPTION
**Pull request by knitzsche**
When joining an external AP from Mgmt portal when network manager has never joined the AP before [1], for example on a brand new image, we need to wait in the handler. This fix injects a 5 sec wait, which works on pi3. Also, disable wifi-ap first iter of the daemon loop to ensure clean state on daemon start/restart.

[1] you can tell whether nm has ever joined the ap with "nmcli c". You can use "nmcli c delete NAME" to clear existing connections to simulate a fresh image condiiton.

I've also added a 40 wait in the first iter of the daemon loop *before* disabling wifi-ap. This seems to deal with a race condition (which I theorize) that only seems to appear on first install. My guess is wifi-ap snap and wifi-connect are both trying to control whether wifi-ap is up/down, which occasionally on first boot got the system into a state where the AP was up but had no ssids (probably because after wifi-connect brought it down in first iter of daemon loop and was waiting, it was then brought up by wifi-ap). So the new wait hopefully allows the system to reach a steady state before continuing. I ran it several times on a fresh image each time and did not hit the problem again.

### CODE REVIEW

**Comment by rmescandon** [comment]
So.. now I don't have troubles in rendering portal just after flashed and installed for the first time (avahi ok, even) even If I don't set explicitly a ssid and passphrase but use default ones. However, after clicking in portal connect button, device seems not to connect to external network. However it does if I ssh through eth port and wifi-connect.netman
On the other hand, once connected to external network, If I type wifi-connect.wifi-ap -ap-on I see in settings disabled: false but network is still connected to external and AP is not getting up. Actually, Device can be connected to external wifi and have disabled: false setting at the same time. Not sure if this is correct

**Comment by arapulido** [comment]
I have also some issues

 * I run console conf via ethernet
 * I am able to run AP mode and connect to the network
 * I am also able to access the portal
 * But it looks like the connection never happens. It brings down the AP, but when I ssh into the device through ethernet, nmcli c returns an empty list

**Comment by arapulido** [comment]
Today, I tried to set up AP again by doing -ap-on. It waited several minutes, but it didn't bring it on.

Then I restarted the daemon service, and it was on.

**Comment by knitzsche** [comment]
added a 5 sec wait after changing managed state of iface to give netman time to complete before we use it, which fixes the failure to connect to external ap from portal.

notes:
* "sudo journalctl -f | grep ==" is useful to watch state and other mgs.
* Using commands AND daemon might lead to inconsistent states. For example wifi-ap up/down needs to be coordinated with netman owning the iface or not.  Most commands are really for devel/prototype.

**Comment by rmescandon** [comment]
Now worked for me.

**Pull request merged**
